# Generated by Django 2.0.6 on 2019-11-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_sell_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garagesellmodel',
            name='description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
