# Generated by Django 2.0.6 on 2019-11-04 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage_sell_app', '0002_garagesellmodel_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garagesellmodel',
            old_name='description',
            new_name='item_name',
        ),
    ]
